ignore = [
    "tests/bcfiles",
]

unstable_features = true

imports_layout = "HorizontalVertical"

match_block_trailing_comma = true

newline_style = "Unix"

spaces_around_ranges = true

use_field_init_shorthand = true
